#!/bin/bash

set -e -u

rm -f config/config.yml
ln -s ../../container-networking-deployments/datadog/config.yml config/config.yml

bundle exec rake toque:push
bundle exec rake pickelhelm:push
bundle exec rake mitre:push

rm -f config/config.yml
